package ru.trandefil.tm.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-07T10:42:57.183+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "SimpleWebServerService",
        wsdlLocation = "http://localhost:8080/simpleWebService?wsdl",
        targetNamespace = "http://test.tm.trandefil.ru/")
public class SimpleWebServerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.tm.trandefil.ru/", "SimpleWebServerService");
    public final static QName SimpleWebServerPort = new QName("http://test.tm.trandefil.ru/", "SimpleWebServerPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/simpleWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SimpleWebServerService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/simpleWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimpleWebServerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimpleWebServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleWebServerService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SimpleWebServerService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SimpleWebServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SimpleWebServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns SimpleWebServer
     */
    @WebEndpoint(name = "SimpleWebServerPort")
    public SimpleWebServer getSimpleWebServerPort() {
        return super.getPort(SimpleWebServerPort, SimpleWebServer.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SimpleWebServer
     */
    @WebEndpoint(name = "SimpleWebServerPort")
    public SimpleWebServer getSimpleWebServerPort(WebServiceFeature... features) {
        return super.getPort(SimpleWebServerPort, SimpleWebServer.class, features);
    }

    public static void main(String[] args) {
        System.out.println(new SimpleWebServerService().getSimpleWebServerPort().sum(10,20));
    }

}
