package ru.trandefil.tm.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-07T18:30:44.425+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://test.tm.trandefil.ru/", name = "SimpleWebServer")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleWebServer {

    @WebMethod
    @Action(input = "http://test.tm.trandefil.ru/SimpleWebServer/sumRequest", output = "http://test.tm.trandefil.ru/SimpleWebServer/sumResponse")
    @RequestWrapper(localName = "sum", targetNamespace = "http://test.tm.trandefil.ru/", className = "ru.trandefil.tm.test.Sum")
    @ResponseWrapper(localName = "sumResponse", targetNamespace = "http://test.tm.trandefil.ru/", className = "ru.trandefil.tm.test.SumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sum(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b
    );

    @WebMethod
    @Action(input = "http://test.tm.trandefil.ru/SimpleWebServer/divRequest", output = "http://test.tm.trandefil.ru/SimpleWebServer/divResponse")
    @RequestWrapper(localName = "div", targetNamespace = "http://test.tm.trandefil.ru/", className = "ru.trandefil.tm.test.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://test.tm.trandefil.ru/", className = "ru.trandefil.tm.test.DivResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int div(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b
    );
}
