package ru.trandefil.tm.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-07T17:02:23.449+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://api.tm.trandefil.ru/", name = "ProjectEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndPoint {

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/getByNameRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/getByNameResponse")
    @RequestWrapper(localName = "getByName", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetByName")
    @ResponseWrapper(localName = "getByNameResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.api.Project getByName(
        @WebParam(name = "projectName", targetNamespace = "")
        java.lang.String projectName
    );

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/saveRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/saveResponse")
    @RequestWrapper(localName = "save", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.api.Project save(
        @WebParam(name = "project", targetNamespace = "")
        ru.trandefil.tm.api.Project project
    );

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/deleteByNameRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/deleteByNameResponse")
    @RequestWrapper(localName = "deleteByName", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.DeleteByName")
    @ResponseWrapper(localName = "deleteByNameResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.DeleteByNameResponse")
    public void deleteByName(
        @WebParam(name = "projectName", targetNamespace = "")
        java.lang.String projectName
    );

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/deleteRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/deleteResponse")
    @RequestWrapper(localName = "delete", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.DeleteResponse")
    public void delete(
        @WebParam(name = "project", targetNamespace = "")
        ru.trandefil.tm.api.Project project
    );

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/getAllRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.trandefil.tm.api.Project> getAll();

    @WebMethod
    @Action(input = "http://api.tm.trandefil.ru/ProjectEndPoint/getByIdRequest", output = "http://api.tm.trandefil.ru/ProjectEndPoint/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://api.tm.trandefil.ru/", className = "ru.trandefil.tm.api.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.api.Project getById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
