package ru.trandefil.tm.generatied;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-08T09:25:51.983+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://generatied.tm.trandefil.ru/", name = "ProjectEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndPoint {

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/deleteByNameRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/deleteByNameResponse")
    @RequestWrapper(localName = "deleteByName", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.DeleteByName")
    @ResponseWrapper(localName = "deleteByNameResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.DeleteByNameResponse")
    public void deleteByName(
        @WebParam(name = "projectName", targetNamespace = "")
        java.lang.String projectName
    );

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/saveRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/saveResponse")
    @RequestWrapper(localName = "save", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.generatied.Project save(
        @WebParam(name = "project", targetNamespace = "")
        ru.trandefil.tm.generatied.Project project
    );

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getByNameRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getByNameResponse")
    @RequestWrapper(localName = "getByName", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetByName")
    @ResponseWrapper(localName = "getByNameResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.generatied.Project getByName(
        @WebParam(name = "projectName", targetNamespace = "")
        java.lang.String projectName
    );

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/deleteRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/deleteResponse")
    @RequestWrapper(localName = "delete", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.DeleteResponse")
    public void delete(
        @WebParam(name = "project", targetNamespace = "")
        ru.trandefil.tm.generatied.Project project
    );

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getAllRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.trandefil.tm.generatied.Project> getAll();

    @WebMethod
    @Action(input = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getByIdRequest", output = "http://generatied.tm.trandefil.ru/ProjectEndPoint/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://generatied.tm.trandefil.ru/", className = "ru.trandefil.tm.generatied.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.trandefil.tm.generatied.Project getById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );
}
